#define NB_DATA 180

#include <time.h>
#include <stdlib.h>

#include <stdio.h>
#include <signal.h>
#include <unistd.h>
#include <sys/mman.h>
#include <native/task.h>
#include <native/timer.h>

#include <pthread.h>

void reception_task(int tab[]){
	int i;
	for(i = 0; i<NB_DATA;i++){
		tab[i]=(rand()%180);
	}
}

void computation_task(int *tab1, int *tab2){
	int i;
	for(i=0; i<NB_DATA;i++){
		if (tab1[i]>7){
			tab2[i] = tab1[i];
		} else{
			tab2[i] = 0;
		}
		//printf("%d - ", tab2[i]);
	}
	//printf("\n");
}

void print_task(int *tab){
/**** this task display the obstacle array ****/
	int i;
	char result[NB_DATA];
	for(i=0;i<NB_DATA;i++){
		result[i]=(tab[i]!=0)?' ':'*';
		//printf("%c", result[i]);
	}
	//printf("\n");
}



int running = 1;
int data[NB_DATA];
int obstacle[NB_DATA];

pthread_t sequence;

void* sequential_thread(void* arg){
	while(running){
		printf("reception task \n");
		reception_task(data);
		usleep(100000);

		printf("computation task\n");
		computation_task(data, obstacle);
		usleep(250000);

		printf("print task\n");
		print_task(obstacle);
	}
}


int main(int argc, char* argv[]){

	mlockall(MCL_CURRENT|MCL_FUTURE);

	if (argc<2){
		printf("arguments not found - usage : exec <tps in sec>\n");
		return 1;
	}

	printf("beginning main Thread.\n");
	int temp = atoi(argv[1]);

	// we give a constant time_t in order to have always the same data generated by generation Task
	time_t today_time = 1397131000;
	srand(today_time);

	/*************sequential mode********************/

	pthread_create(&sequence, NULL, &sequential_thread, NULL);
	printf("sleeping %ds ...\n", temp);
	
	sleep(temp);
	running=0;
	printf("...stopping threads !\n");
	
	running=0;
	
	pthread_join(sequence, NULL);

	return 0;
}
