/******* need to compile with the option "-lpthread"   ********/

#define NB_DATA 180

#include <signal.h>
#include <unistd.h>

#include <native/cond.h>
#include <native/mutex.h>
#include <native/task.h>
#include <native/timer.h>
#include <time.h>
#include <stdlib.h>
#include <stdio.h>



void reception_task(int tab[]){
	int i;
	for(i = 0; i<180;i++){
		tab[i]=(rand()%180);
	}
}

void computation_task(int *tab1, int *tab2){
	int i;
	for(i=0; i<180;i++){
		if (tab1[i]>7){
			tab2[i] = tab1[i];
		} else{
			tab2[i] = 0;
		}
		//printf("%d - ", tab2[i]);
	}
	//printf("\n");
}

void print_task(int *tab){
/**** this task display the obstacle array ****/
	int i;
	char result[180];
	for(i=0;i<180;i++){
		result[i]=(tab[i]!=0)?' ':'*';
		//printf("%c", result[i]);
	}
	//printf("\n");
}


void reception_RTtask(void* arg);
void computation_RTtask(void* arg);
void print_RTtask(void* arg);


/*************** variable *************************/
RT_TASK reception, computation, print_data;
RT_MUTEX data_tab, obst_tab;
RT_COND new_data, to_print;

//running is the boolean for keeping alive thread
int running=1;
//data_old give an indication to know if data_tab has been already compute by compute_task or not
int data_old=0;

//the 2 tabs of data for the system
int data[NB_DATA];
int obstacle[NB_DATA];


/**************** threads ***************************/
void reception_RTtask(void* arg){
	while(running){
		
		rt_mutex_acquire(&data_tab, NULL);
		

		printf("reception task \n");
		reception_task(data);
		data_old=0;


		rt_mutex_release(&data_tab);

		//signaling that the data in tab are updated with new value 
		rt_cond_signal(&new_data);
		
		usleep(100000);
	}	
}

void computation_RTtask(void* arg){
	while(running){
		
		rt_mutex_acquire(&data_tab, NULL);
		rt_mutex_acquire(&obst_tab, NULL);
		

		// if data in the data tab are already read it's waiting until new data arrives
		if(data_old==1){
			printf("... waiting ... tab has no new data\n");
			rt_cond_wait(&new_data, &data_tab, NULL);
		}

		printf("computation task\n");
		computation_task(data, obstacle);
		data_old=1;


		rt_mutex_release(&data_tab);
		rt_mutex_release(&obst_tab);

		//it asks thread to print new obstacles data
		rt_cond_signal(&to_print);
		
		usleep(250000);
	}
}

void print_RTtask(void* arg){
	while(running){

		pthread_mutex_lock(&obst_tab);


		rt_cond_wait(&to_print, &obst_tab, NULL);
		printf("print task\n");
		print_task(obstacle);


		pthread_mutex_unlock(&obst_tab);
	}
}




int main(int argc, char* argv[]){

	mlockall(MCL_CURRENT|MCL_FUTURE);

	if (argc<2){
		printf("arguments not found - usage : exec <tps in sec>\n");
		return 1;
	}

	printf("beginning main Thread.\n");
	
	int temp = atoi(argv[1]);

	// we give a constant time_t in order to have always the same data generated by generation Task
	time_t today_time = 1397131000;
	srand(today_time);
	
	// initialize mutex and conditions
	if ((rt_mutex_create(&data_tab, NULL) != 0) &&( rt_mutex_create(&obst_tab, NULL) != 0)	 ){
		printf("\n mutex init failed.\n");
		return 1;
	}
	
	if((rt_cond_create(&new_data, NULL) != 0) || (rt_cond_create(&to_print, NULL))){
		printf("\n initialisation of condition failed.\n");
	
	}

	// creation of the differents threads
	rt_task_create(&reception, NULL, 0, 99, 0);
	rt_task_create(&computation, NULL,0, 99, 0);
	rt_task_create(&print_data, NULL,0, 99, 0);
	
	rt_task_start(&reception, &reception_RTtask, NULL);
	rt_task_start(&computation, &computation_RTtask, NULL);
	rt_task_start(&print_data, &print_RTtask, NULL);

	// the main thread had to wait a little and then stop child threads
	printf("sleeping %ds ...\n", temp);
	
	sleep(temp);
	printf("...stopping threads !\n");
	
	running=0;
	
	rt_task_join(&reception);
    rt_task_join(&computation);
    rt_task_join(&print_data);
   
    rt_mutex_delete(&data_tab);
    rt_mutex_delete(&obst_tab);
    
    rt_cond_delete(&new_data);
    rt_cond_delete(&to_print);
	printf("end of the main Thread\n");
	return 0;
}
